version: '3'

dotenv: ['.env']

includes:
  podman:
    taskfile: ./deploy/podman/Taskfile.yaml
    dir: ./deploy/podman
    aliases: [pd]
  cli:
    taskfile: ./cli/Taskfile.yaml
    dir: ./cli
  server:
    taskfile: ./server/Taskfile.yaml
    dir: ./server
  proto:
    taskfile: ./proto/Taskfile.yaml
    dir: ./proto

tasks:
  dev:
    desc: Start full dev environment (containers + server)
    cmds:
      - task: podman:dev:start
      - defer: { task: podman:dev:stop }
      - task: server:run

  test:all:
    desc: Run all tests (unit, integration, e2e) across all projects
    cmds:
      - task: cli:test:all
      - task: server:test:all
