version: '3'

dotenv: ['.env']

includes:
  podman:
    taskfile: ./deploy/podman/Taskfile.yaml
    dir: ./deploy/podman
    aliases: [pd]
  cli:
    taskfile: ./cli/Taskfile.yaml
    dir: ./cli
  server:
    taskfile: ./server/Taskfile.yaml
    dir: ./server
  proto:
    taskfile: ./proto/Taskfile.yaml
    dir: ./proto

tasks:
  test:
    desc: Run all tests (unit, integration, e2e) across all projects
    cmds:
      - task: server:test:integration
      - task: server:test:e2e
      - task: cli:test:unit
      - task: cli:test:e2e
