version: '3'

dotenv: ['.env']

includes:
  podman:
    taskfile: ./deploy/podman/Taskfile.yaml
    dir: ./deploy/podman
    aliases: [pd]
  server:
    taskfile: ./server/Taskfile.yaml
    dir: ./server
  proto:
    taskfile: ./proto/Taskfile.yaml
    dir: ./proto
