version: '3'

vars:
  DB_HOST: '{{.DB_HOST | default "localhost"}}'
  DB_PORT: '{{.DB_PORT | default "5432"}}'
  TEST_DBSTRING: 'host={{.DB_HOST}} port={{.DB_PORT}} user={{.POSTGRES_USER}} password={{.POSTGRES_PASSWORD}} dbname={{.POSTGRES_DB}} sslmode=disable'

env:
  GOOSE_DRIVER: postgres
  GOOSE_MIGRATION_DIR: ./pkg/store/postgres/migrations
  GOOSE_DBSTRING: '{{.TEST_DBSTRING}}'
  TEST_DBSTRING: '{{.TEST_DBSTRING}}'

tasks:
  build:
    desc: Build the server binary
    cmds:
      - go build -o ./infrapad-server .
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - ./infrapad-server

  run:
    desc: Start the gRPC server
    deps: [build]
    cmds:
      - ./infrapad-server start --db "{{.TEST_DBSTRING}}" {{.CLI_ARGS}}

  db:migrate:status:
    desc: Show status of migrations
    cmds:
      - goose status

  db:migrate:up:
    desc: Apply all pending migrations
    cmds:
      - goose up

  db:migrate:up-by-one:
    desc: Apply the next pending migration
    cmds:
      - goose up-by-one

  db:migrate:down:
    desc: Roll back the last applied migration
    cmds:
      - goose down

  db:migrate:reset:
    desc: Roll back all migrations
    cmds:
      - goose reset

  db:migrate:redo:
    desc: Roll back and re-apply the last migration
    cmds:
      - goose redo

  db:migrate:create:
    desc: "Create a new migration file (usage: task db:migrate:create -- name)"
    cmds:
      - goose create -s {{.CLI_ARGS}} sql

  test:all:
    desc: Run all tests (intergration, e2e)
    cmds:
      - task: test:integration
      - task: test:e2e

  test:integration:
    desc: "Run integration tests (usage: task test:integration [-- --run TestName ...])"
    cmds:
      - go test -v {{.CLI_ARGS}} ./test/integration

  test:e2e:
    desc: "Run e2e tests (usage: task test:e2e [-- --run TestName ...])"
    cmds:
      - go test -v {{.CLI_ARGS}} ./test/e2e

  test:e2e:force_skipped:
    desc: "Run e2e tests including ones normally skipped (usage: task test:e2e:force_skipped [-- --run TestName ...])"
    env:
      FORCE_SKIPPED: "1"
    cmds:
      - go test -v {{.CLI_ARGS}} ./test/e2e
