version: '3'

tasks:
  generate:
    desc: Generate Go stubs and OpenAPI specs from proto definitions
    cmds:
      - find gen/go \( -name '*.pb.go' -o -name '*.pb.gw.go' \) -delete
      - buf generate
    sources:
      - "**/*.proto"
      - buf.gen.yaml
      - buf.yaml
    generates:
      - "gen/go/**/*.go"
      - "../docs/openapi/*.yaml"
