services:
  dummy-auth-proxy:
    profiles:
      - auth-dummy
    build:
      context: ./dummy-auth
      dockerfile: Containerfile
    # See openshift-oauth-proxy.yaml for explanation
    network_mode: host
    command:
      - proxy
      - --listen=127.0.0.1:8089
      - --upstream=http://127.0.0.1:8088
    healthcheck:
      test:
        - CMD
        - /dummy-auth
        - healthcheck
        - --url=http://127.0.0.1:8089/oauth/healthz
      interval: 10s
      timeout: 5s
      retries: 3
